import { Container, Section } from 'components';
import img from 'images/img';
import {
  AboutSpan,
  AboutText,
  AboutTitle,
  IconSharp,
  IconSharpBanner,
  Picture,
  Span,
  SpanAboutText,
  Text,
  TextBanner,
  WrapBanner,
  WrapIcon,
  WrapMobil,
  WrapTable,
} from './About.styled';
const { monkey2_d, monkey2_t, monkey2_m, monkey2_d_2x, monkey2_t_2x, monkey2_m_2x } = img;

export const About = () => {
  return (
    <>
      <Container>
        <Section id="about" aria-label="About Section" role="region">
          <WrapMobil>
            <AboutTitle>
              a Story that started with{' '}
              <AboutSpan>
                one simple <Span> ape </Span>
              </AboutSpan>
            </AboutTitle>
            <AboutText>
              WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING
              AND DYNAMIC JOURNEY ON THE YACHT
            </AboutText>
            <WrapIcon>
              <IconSharp />
            </WrapIcon>
            <Text>
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE RANDOMLY
              GENERATED BY USERS
            </Text>
            <Picture aria-label="Monkey Picture">
              <source
                type="image/png"
                media="(max-width: 767px)"
                srcSet={`${monkey2_m} 1x, ${monkey2_m_2x} 2x`}
              />
              <img src={`${monkey2_m}`} alt="Рicture monkey" />
            </Picture>
          </WrapMobil>
          <WrapTable>
            <div>
              <AboutTitle>
                a Story that started with{' '}
                <AboutSpan>
                  one simple <Span>ape</Span>
                </AboutSpan>
              </AboutTitle>
              <WrapIcon>
                <IconSharp />
              </WrapIcon>
              <Text>
                EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE RANDOMLY
                GENERATED BY USERS
              </Text>
            </div>
            <div>
              <AboutText>
                WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF
                ESCAPING AND DYNAMIC JOURNEY ON THE <SpanAboutText> YACHT</SpanAboutText>
              </AboutText>
              <Picture aria-label="Monkey Picture">
                <source
                  type="image/png"
                  media="(max-width: 1279px)"
                  srcSet={`${monkey2_t} 1x, ${monkey2_t_2x} 2x`}
                />
                <source
                  type="image/png"
                  media="(min-width: 1280px)"
                  srcSet={`${monkey2_d} 1x, ${monkey2_d_2x} 2x`}
                />
                <img src={`${monkey2_d}`} alt="Рicture monkey" />
              </Picture>
            </div>
          </WrapTable>
        </Section>
      </Container>
      <WrapBanner aria-label="Banner Section" role="region">
        <TextBanner>
          troy stereotypes
          <IconSharpBanner />
          HAVE NO LIMITS
          <IconSharpBanner />
          Break rules
          <IconSharpBanner />
        </TextBanner>
      </WrapBanner>
    </>
  );
};
